server:
  port: ${PORT:8080}
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: vgshop
  datasource:
    url: jdbc:postgresql://ep-fragrant-river-a43r676b-pooler.us-east-1.aws.neon.tech:5432/verceldb
    username: default
    password: DwvOtYTj3cP9
    driver-class-name: org.postgresql.Driver
